name: bitsdojo_windows
description: bitsdojo_windows
version: 1.0.0
author: fangzhao
homepage: http://git.vnnox.net/
publish_to: http://172.16.82.51:8080

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: bitsdojo_window_windows
#      macos:
#        default_package: bitsdojo_window_macos
#      linux:
#        default_package: bitsdojo_window_linux

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/fefz/bitsdojo_window
      ref: local-path
      path: bitsdojo_window_platform_interface/
  bitsdojo_window_windows:
    git:
      url: https://github.com/fefz/bitsdojo_window
      ref: local-path
      path: bitsdojo_window_windows/
#  bitsdojo_window_macos:
#    git:
#      url: https://github.com/fefz/bitsdojo_window
#      ref: local-path
#      path: bitsdojo_window_macos/
#  bitsdojo_window_linux:
#    git:
#      url: https://github.com/fefz/bitsdojo_window
#      ref: local-path
#      path: bitsdojo_window_linux/
